# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b3ea56562d7969b6042f62790435dce1f4ddb31e81cbbc40f9949f8bcd932f9d6c32e07af9e0ed97f69df9bc8176b2fe2fb409a84020517ee2b21a63ddefb90

test:
  secret_key_base: a5ee4c217f0f7398ae5c8281b62ffd67ff4c69642456365c728dc4d511273000231b20edf798e9e0598d89b5e7b7f4816cdb1856cf11619bc6c797f3ff255b0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
